version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    entrypoint: "bash"
    networks:
      - experiment
  server:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    entrypoint: "bash"
    networks:
      - experiment

networks:
  experiment:
